services:
  db:
    image: postgres:15
    container_name: maslyhan_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
      POSTGRES_DB: hotel_db
    volumes:
      - ./hoteldata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel_pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123

  python:
    build: C:\Users\Vitaliy\KPPython\Lab9
    image: python:3.11
    container_name: hotel_python
    depends_on:
      - db
    volumes:
      - C:\Users\Vitaliy\KPPython\Lab9:/app
    working_dir: /app
    command: tail -f /dev/null